services:
  miamtrix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miamtrix_bot
    restart: unless-stopped
    env_file:
      - /keybase/team/epfl_matrix/.env
    volumes:
      - ./data:/data
