services:
  miamtrix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miamtrix_bot
    restart: unless-stopped
    environment:
      - URI_API=${URI_API}
      - API_PASSWORD=${API_PASSWORD}
      - API_USERNAME=${API_USERNAME}
      - URL_SERVER_MATRIX=${URL_SERVER_MATRIX}
      - USERNAME_BOT=${USERNAME_BOT}
      - PASSWORD_BOT=${PASSWORD_BOT}
    volumes:
      - ./data:/data
