name: Build image at new release

on:
  release:
    types: released

env:
  REGISTRY_PATH: 'quay-its.epfl.ch/svc0176/miamtrix'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: login quay
        run: echo ${{ secrets.quay_password }} | docker login -u ${{ secrets.quay_bot_user }} --password-stdin quay-its.epfl.ch

      - name: get version
        id: version
        uses: rabbitson87/get-cargo-package-info@v1

      - name: build image
        run: docker build -t ${{ env.REGISTRY_PATH }}:{{ steps.version.outputs.version }} .

      - name: push image on quay
        run: |
            docker push ${{ env.REGISTRY_PATH }}:latest
            docker push ${{ env.REGISTRY_PATH }}:{{ steps.version.outputs.version }}
